### ISSUE TITLE
Quick Join Mode

### ISSUE THREAD

**Issue by SmilerRyan** [mattieFM/AmongJS#2]
Whilst starting the game, it takes a while with the animations and warnings etc.
It would be nice if we could use a simple command paramater to load straight into the map and join the server.

Example command: ``client.exe --join localhost:port``
Example output: 
```
Name (less than 15 characters): 
Hat number (not vent/chracter/2): 
Joining server localhost:port...

[Map Shows Here]
```

**Comment by SmilerRyan** [comment]
Did not notice the documentation if releases, seems to have this ability already.

**Comment by mattieFM** [comment]
adding "-SkipAll" to your launch command will launch the game without any flavor text only asking you for the required inputs to join a game
